receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlphttp/to_jaeger:
    endpoint: "http://jaeger:4318"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"
  logging:
    loglevel: info

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/to_jaeger, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]