receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  
  debug:
    verbosity: detailed 

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] 
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]